apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: traine-schedule
        image:  $registry:$BUILD_NUMBER
        ports:
        - name: train-port
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
spec:
  ports:
  - port: 3000
    targetPort: train-port
    nodePort: 32000
    protocol: TCP
  selector:
    app: train-schedule
  type: NodePort

